# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/search/service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/search/service.proto", :syntax => :proto3) do
    add_message "github.minimaltwirp.rpc.SearchRequest" do
      optional :user_query, :string, 2
      optional :repository_id, :uint64, 3
    end
    add_message "github.minimaltwirp.rpc.SearchResponse" do
      optional :results, :string, 1
    end
  end
end

module Github
  module Minimaltwirp
    module Rpc
      SearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.minimaltwirp.rpc.SearchRequest").msgclass
      SearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("github.minimaltwirp.rpc.SearchResponse").msgclass
    end
  end
end
